services:
  rabbitmq-notification:
    image: rabbitmq:4-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672" # RabbitMQ management UI
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS:-guest}

  api-service:
    build:
      context: ./api-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      rabbitmq-notification:
        condition: service_healthy

  email-service:
    build:
      context: ./email-service
      dockerfile: Dockerfile
    depends_on:
      rabbitmq-notification:
        condition: service_healthy

  sms-service:
    build:
      context: ./sms-service
      dockerfile: Dockerfile
    depends_on:
      rabbitmq-notification:
        condition: service_healthy
